common/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views
from . import views
app_name = 'common'
urlpatterns = [
    # path('login/', auth_views.LoginView.as_view(template_name = 'common/login.html'), name='login'),
    path('login/', views.login_view, name='login'),

    path('logout/', views.logout_view, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('category/<int:category_id>', views.category, name='category'),
    # path('mypage/', views.profile, name='mypage'),
    path('profile_update/', views.profile_update, name='profile_update'),
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='registration/password_reset_form.html', success_url=reverse_lazy('common:password_reset_done')), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(success_url = reverse_lazy('common:password_reset_complete')), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('profile/<int:user_id>', views.profile, name='profile'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from pybo.views import base_views
from django.conf import settings # 추가

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')),
    path('common/', include('common.urls')), # 추가
    path('', base_views.index, name = 'index'),
    path('accounts/', include('allauth.urls')), # 추가
    # path('accounts/', include('accounts.urls')), # 추가
]
if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

pybo/urls.py
from django.urls import path
from .views import base_views, question_views, answer_views

app_name = 'pybo'

urlpatterns = [
    path('', base_views.index, name = 'index'),
    path('<int:question_id>/', base_views.detail, name = 'detail'),
    path('answer/create/<int:question_id>/', answer_views.answer_create, name = 'answer_create'),
    path('question/create/', question_views.question_create, name = 'question_create'),
    path('question/modify/<int:question_id>/', question_views.question_modify, name = 'question_modify'),
    path('question/delete/<int:question_id>/', question_views.question_delete, name = 'question_delete'),
    path('answer/modify/<int:answer_id>/', answer_views.answer_modify, name = 'answer_modify'),
    path('answer/delete/<int:answer_id>/', answer_views.answer_delete, name = 'answer_delete'),
    path('question/vote/<int:question_id>/', question_views.question_vote, name = 'question_vote'),
    path('answer/vote/<int:answer_id>/', answer_views.answer_vote, name = 'answer_vote'),
    path('comment/create/question/<int:question_id>/', question_views.comment_create_question, name = 'comment_create_question'),
    path('answer/comment/create/<int:answer_id>/', answer_views.comment_create_answer, name = 'comment_create_answer'),
]

pybo/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class Question(models.Model):
    author = models.ForeignKey(User, on_delete = models.CASCADE, related_name='author_question')
    subject = models.CharField(max_length=200)
    content = models.TextField()
    create_date = models.DateTimeField(db_index=True)
    # create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    voter = models.ManyToManyField(User, related_name='voter_question')
    comment = models.ManyToManyField('Comment', related_name='comment_question')
    category = models.ForeignKey('Category', on_delete = models.SET_NULL, null=True, blank=True)
    hits = models.IntegerField(default=0)
    def __str__(self):
        return self.subject

class Answer(models.Model):
    author = models.ForeignKey(User, on_delete = models.CASCADE, related_name='author_answer')
    question = models.ForeignKey(Question, on_delete = models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField(db_index=True)
    modify_date = models.DateTimeField(null=True, blank=True)
    voter = models.ManyToManyField(User, related_name='voter_answer')
    voter_count = models.IntegerField(default=0)
    comment = models.ManyToManyField('Comment', related_name='comment_answer')

class Category(models.Model):
    name = models.CharField(max_length=50, unique=True)
    
class Comment(models.Model):
    author = models.ForeignKey(User, on_delete = models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()
    question = models.ForeignKey(Question, on_delete = models.CASCADE, null=True, blank=True, related_name='question_comment')
    answer = models.ForeignKey(Answer, on_delete = models.CASCADE, null=True, blank=True, related_name='answer_comment')

pybo/views/answer_views.py
from django.shortcuts import render, get_object_or_404, redirect, resolve_url
from django.utils import timezone
from ..models import Question, Answer
from ..forms import AnswerForm, CommentForm
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .base_views import render_with_common
from django.core.paginator import Paginator

@render_with_common
@login_required(login_url='common:login')
def answer_create(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.method == 'POST':
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.author = request.user
            answer.create_date = timezone.now()
            answer.question = question
            answer.save()
            return redirect('{}#answer_{}'.format(resolve_url('pybo:detail', question_id=question.id), answer.id))

    else:
        form = AnswerForm()
    context = {'question': question, 'form': form}
    return render(request, 'pybo/question_detail.html', context=context)

@render_with_common
@login_required(login_url='common:login')
def answer_modify(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user != answer.author:
        messages.error(request, '수정 권한이 없습니다')
        return redirect('pybo:detail', question_id=answer.question.id)
    
    if request.method == 'POST':
        form = AnswerForm(request.POST, instance=answer)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.modify_date = timezone.now()
            answer.save()
            return redirect('{}#answer_{}'.format(
    resolve_url('pybo:detail', question_id=answer.question.id), answer.id))

    else:
        form = AnswerForm(instance=answer)
    context = {'answer': answer, 'form': form}
    return render(request, 'pybo/answer_form.html', context=context)

@render_with_common
@login_required(login_url='common:login')
def answer_delete(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user != answer.author:
        messages.error(request, '삭제 권한이 없습니다')
    else:
        answer.delete()
    return redirect('pybo:detail', question_id=answer.question.id)

@render_with_common
@login_required(login_url='common:login')
def answer_vote(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user == answer.author:
        messages.error(request, '본인이 작성한 답변은 추천할 수 없습니다')
    else:
        answer.voter.add(request.user)
    return redirect('{}#answer_{}'.format(
    resolve_url('pybo:detail', question_id=answer.question.id), answer.id))

@render_with_common
@login_required(login_url='common:login')
def comment_create_answer(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.create_date = timezone.now()
            comment.answer = answer
            comment.save()
            answer.comment.add(comment)
            answer.save()
            return redirect('{}#comment_{}'.format(
    resolve_url('pybo:detail', question_id=answer.question.id), comment.id))
    else:
        form = CommentForm()
    context = {'answer': answer, 'form': form}
    return {'context': context, 'template': 'pybo/answer_detail.html'}

@render_with_common
def recent_answer(request):
    answer_list = Answer.objects.order_by('-create_date')
    paginator = Paginator(answer_list, 10)
    page_object = paginator.get_page(1)
    context = {'answer_list': page_object}
    return {'context': context, 'template': 'pybo/recent_answer.html'}

pybo/views/base_views.py
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from ..models import Question, Comment
from django.shortcuts import get_object_or_404
from django.db.models import Q, Count
from pybo.decorators import render_with_common, log_time
from django.core.cache import cache
from django.conf import settings
import redis
from ..cache_functions import save_dict_to_redis_as_string, get_dict_from_redis_string, get_element_from_redis_dict, add_to_redis_dict
import pickle

redis_client = redis.StrictRedis.from_url(settings.CACHES["default"]["LOCATION"])
# Create your views here.
def cache_page(page_obj, key):
    serialized_page = pickle.dumps(page_obj)
    redis_client.set(key, serialized_page)

def get_cached_page(key):
    serialized_page = redis_client.get(key)
    if serialized_page:
        return pickle.loads(serialized_page)
    return None

@log_time
@render_with_common
def index(request):
    page = request.GET.get('page', '1')
    kw = request.GET.get('kw', '')
    # redis_client.delete('index')
    # redis_client.delete('page_1')
    if not kw:
        cached_question_list = get_element_from_redis_dict("index", page)

        question_page_ids = cached_question_list
        page_object = get_cached_page(f"page_{page}")
    if kw or not cached_question_list:
        if kw:
            question_list = Question.objects.order_by('-create_date')
            question_list = question_list.filter(
                Q(subject__icontains=kw) |
                Q(content__icontains=kw) |
                Q(answer__content__icontains=kw) |
                Q(author__username__icontains=kw) |
                Q(answer__author__username__icontains=kw)
            ).distinct()
        else:
            question_list = Question.objects.only('id').order_by('-create_date')
        print(f">> 쿼리: {question_list.query}")

        paginator = Paginator(question_list, 10)

        try:
            page_object = paginator.page(page)
        except PageNotAnInteger:
            page_object = paginator.page(1)
        except EmptyPage:
            page_object = paginator.page(paginator.num_pages)
        print(f">> typeof page_object: {type(page_object)}")
        if not kw:
            question_page_ids = [q.id for q in page_object.object_list]
            add_to_redis_dict("index", page, question_page_ids)
            cache_page(page_object, f"page_{page}")
    else:
        print("using cache")

    questions = Question.objects.filter(id__in=question_page_ids).select_related('author').prefetch_related('answer_set').order_by('-create_date')
    print(f">> 쿼리: {questions.query}")
    context = {'pagination': page_object, 'question_list': questions, 'page': page, 'kw' : kw}

    return {'context': context, 'template': 'pybo/question_list.html'}

@log_time
@render_with_common
def detail(request, question_id):
    page = request.GET.get('page', '1')
    question = get_object_or_404(Question, pk=question_id)
    question.hits += 1
    question.save()
    answer_list = question.answer_set.all().order_by('-voter_count', '-create_date')
    print(f"query of answer_list: {answer_list.query}")
    paginator = Paginator(answer_list, 10)
    page_object = paginator.get_page(page)
    # print("page object %s" % page_object.count)

    context = {'question': question, 'answer_list': page_object}
    return {'context': context, 'template': 'pybo/question_detail.html'}

@log_time
@render_with_common
def recent_comment(request):
    comment_list = Comment.objects.order_by('-create_date')
    paginator = Paginator(comment_list, 10)
    page_object = paginator.get_page(1)
    context = {'comment_list': page_object}
    return {'context': context, 'template': 'pybo/recent_comment.html'}

pybo/views/common_render.py
from functools import wraps
from ..models import Category, Answer, Comment
from django.shortcuts import render

def render_with_common(func):
    @wraps(func)
    def wrapper(request, *args, **kwargs):
        print(">>function: ", func.__name__)
        request_data = func(request, *args, **kwargs)
        print(">>request_data: ", request_data)
        if isinstance(request_data, dict):
            recent_answers = Answer.objects.order_by('-create_date')[:5]
            recent_comments = Comment.objects.order_by('-create_date')[:5]
            additional_data = {'category_list': Category.objects.all(), 'recent_answers': recent_answers, 'recent_comments': recent_comments}
            request_data['context'].update(additional_data)
            return render(request, request_data['template'], request_data['context'])
        return request_data
    return wrapper

pybo/views/question_views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from ..models import Question, Category
from ..forms import QuestionForm, CommentForm
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .base_views import render_with_common
from django.db import transaction
import redis
from django.conf import settings
from django.core.cache import cache

# Redis 연결 설정
redis_client = redis.StrictRedis.from_url(settings.CACHES['default']['LOCATION'])

@render_with_common
@login_required(login_url='common:login')
def question_create(request):
    if request.method == 'POST':
        form = QuestionForm(request.POST)
        if form.is_valid():
            question = form.save(commit=False)
            question.author = request.user
            question.create_date = timezone.now()
            # print(">>", form.cleaned_data['category'])
            question.category = form.cleaned_data['category']
            # question.category = Category.objects.get(pk = form.cleaned_data['category'])
            question.save()
            redis_client.rpush('index', question.id)
            redis_client.expire('index', 60)
            return redirect('pybo:index')
    else:
        form = QuestionForm()
    context = {'form': form}
    return {'context': context, 'template': 'pybo/question_form.html'}
@render_with_common
@login_required(login_url='common:login')
def question_modify(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.user != question.author:
        messages.error(request, '수정 권한이 없습니다')
        return redirect('pybo:detail', question_id=question_id)
    
    if request.method == 'POST':
        form = QuestionForm(request.POST, instance=question)
        if form.is_valid():
            question = form.save(commit=False)
            question.modify_date = timezone.now()
            question.save()
            return redirect('pybo:detail', question_id=question_id)
    else:
        form = QuestionForm(instance=question)
    context = {'form': form}
    return {'context': context, 'template': 'pybo/question_form.html'}
@login_required(login_url='common:login')
def question_delete(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.user != question.author:
        messages.error(request, '삭제 권한이 없습니다')
        return redirect('pybo:detail', question_id=question_id)
    question.delete()
    return redirect('pybo:index')

@login_required(login_url='common:login')
def question_vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.user == question.author:
        messages.error(request, '본인이 작성한 글은 추천할 수 없습니다')
    else:
        question.voter.add(request.user)
    return redirect('pybo:detail', question_id=question_id)

@transaction.atomic
@login_required(login_url='common:login')
def comment_create_question(request, question_id):
    if request.method == 'POST':
        form = CommentForm(request.POST)
        question = get_object_or_404(Question, pk=question_id)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.create_date = timezone.now()
            comment.question = question
            comment.save()
            question.comment.add(comment)
            question.save()
            return redirect('pybo:detail', question_id=question_id)
    else:
        form = CommentForm()
    context = {'form': form}
    return render(request, 'pybo/comment_form.html', context=context)

templates/pybo/question_detail.html
{% extends 'base.html' %}
{% load pybo_filter %}
{% block content %}
<div class="container my-3">
    <!-- message 표시 -->
    {% if messages %}
    <div class="alert alert-danger my-3" role="alert">
    {% for message in messages %}
        <strong>{{ message.tags }}</strong>
        <ul><li>{{ message.message }}</li></ul>
    {% endfor %}
    </div>
    {% endif %}
    <!-- 질문 -->
    <h2 class="border-bottom py-2">{{ question.subject }}</h2>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text">{{ question.content|mark }}</div>
            <div class="d-flex justify-content-end">
                {% if question.modify_date %}
                <div class="badge bg-light text-dark p-2 text-start mx-3">
                    <div class="mb-2">modified at</div>
                    <div>{{ question.modify_date }}</div>
                </div>
                {% endif %}
                <div class="badge bg-light text-dark p-2 text-start">
                    <div class="mb-2">{{ question.author.username }}</div>
                    <div>{{ question.create_date }}</div>
                    <div>카테고리: {{ question.category.name }}</div>
                    <div>조회수: {{ question.hits }}</div>
                </div>

            </div>
            <div class="my-3">
                <a href="javascript:void(0)" data-uri="{% url 'pybo:question_vote' question.id  %}"
               class="recommend btn btn-sm btn-outline-secondary"> 추천
                <span class="badge rounded-pill bg-success">{{question.voter.count}}</span>
            </a>
                {% if request.user == question.author %}
                <a href="{% url 'pybo:question_modify' question.id  %}" class="btn btn-sm btn-outline-secondary"> 수정 </a>
                <a href="javascript:void(0)" class="delete btn btn-sm btn-outline-secondary"                 data-uri="{% url 'pybo:question_delete' question.id  %}">삭제</a>
                {% endif %}
            </div>
            <form action="{% url 'pybo:comment_create_question' question.id %}" method="post" class="my-3">
                {% csrf_token %}
                <div class="mb-3">
                    <label for="content" class="form-label">댓글내용</label>
                    <textarea {% if not user.is_authenticated %} disabled {% endif %}
                    name="content" id="content" class="form-control" rows="10"></textarea>
                </div>
                <input type="submit" value="댓글등록" class="btn btn-primary">
            </form>
        </div>
    </div>
    <!-- 질문 댓글 -->
    <h5 class="border-bottom my-3 py-2">{{question.comment.count}}개의 댓글이 있습니다.</h5>
    {% for comment in question.comment.all %}
    <a id="answer_{{ answer.id }}"></a> <!-- 답변 위치로 이동하기 위한 앵커 -->
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text">{{ comment.content|mark }}</div>
            <div class="d-flex justify-content-end">
                {% if comment.modify_date %}
                <div class="badge bg-light text-dark p-2 text-start mx-3">
                    <div class="mb-2">modified at</div>
                    <div>{{ comment.modify_date }}</div>
                </div>
                {% endif %}
                <div class="badge bg-light text-dark p-2 text-start">
                    <div class="mb-2">{{ comment.author.username }}</div>
                    <div>{{ comment.create_date }}</div>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
    <!-- 질문 댓글 끝 -->
    <!-- 답변 -->
    <h5 class="border-bottom my-3 py-2">{{question.answer_set.count}}개의 답변이 있습니다.</h5>
    {% for answer in answer_list %}
    <a id="answer_{{ answer.id }}"></a> <!-- 답변 위치로 이동하기 위한 앵커 -->
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text"">{{ answer.content|mark }}</div>
            <div class="d-flex justify-content-end">
                {% if answer.modify_date %}
                <div class="badge bg-light text-dark p-2 text-start mx-3">
                    <div class="mb-2">modified at</div>
                    <div>{{ answer.modify_date }}</div>
                </div>
                {% endif %}
                <div class="badge bg-light text-dark p-2 text-start">
                    <div class="mb-2">{{ answer.author.username }}</div>
                    <div>{{ answer.create_date }}</div>
                </div>
            </div>
            <div class="my-3">
                <a href="javascript:void(0)" data-uri="{% url 'pybo:answer_vote' answer.id  %}"
                class="recommend btn btn-sm btn-outline-secondary"> 추천
                 <span class="badge rounded-pill bg-success">{{answer.voter.count}}</span>
                </a>
                {% if request.user == answer.author %}
                <a href="{% url 'pybo:answer_modify' answer.id  %}" 
                class="btn btn-sm btn-outline-secondary">수정</a>
                <a href="#" class="delete btn btn-sm btn-outline-secondary "
                data-uri="{% url 'pybo:answer_delete' answer.id  %}">삭제</a>
                {% endif %}
            </div>
            <!-- 답변 댓글 -->
            <h5 class="border-bottom my-3 py-2">{{answer.comment.count}}개의 댓글이 있습니다.</h5>
            {% for comment in answer.comment.all %}
            <div class="card my-3">
                <div class="card-body">
                    <div class="card-text">{{ comment.content|mark }}</div>
                    <div class="d-flex justify-content-end">
                        {% if comment.modify_date %}
                        <div class="badge bg-light text-dark p-2 text-start mx-3">
                            <div class="mb-2">modified at</div>
                            <div>{{ comment.modify_date }}</div>
                        </div>
                        {% endif %}
                        <div class="badge bg-light text-dark p-2 text-start">
                            <div class="mb-2">{{ comment.author.username }}</div>
                            <div>{{ comment.create_date }}</div>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
            <form action="{% url 'pybo:comment_create_answer' answer.id %}" method="post" class="my-3">
                {% csrf_token %}
                <div class="mb-3">
                    <label for="content" class="form-label">댓글 내용</label>
                    <textarea {% if not user.is_authenticated %} disabled {% endif %}
                    name="content" id="content" class="form-control" rows="10"></textarea>
                </div>
                <input type="submit" value="댓글등록" class="btn btn-primary">
            </form>
        </div>
    </div>
    {% endfor %}
    <!-- 답변 등록 -->
    <form action="{% url 'pybo:answer_create' question.id %}" method="post" class="my-3">
        {% csrf_token %}
        <div class="mb-3">
            <label for="content" class="form-label">답변내용</label>
            <textarea {% if not user.is_authenticated %} disabled {% endif %}
            name="content" id="content" class="form-control" rows="10"></textarea>
        </div>
        <input type="submit" value="답변등록" class="btn btn-primary">
    </form>
    <!-- 페이징처리 시작 -->
    <ul class="pagination justify-content-center">
        <!-- 이전페이지 -->
        {% if answer_list.has_previous %}
        <li class="page-item">
            <a class="page-link" data-page="{{ question_list.previous_page_number }}"
           href="javascript:void(0)">이전</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
        </li>
        {% endif %}
        <!-- 페이지리스트 -->
        {% for page_number in answer_list.paginator.page_range %}
        {% if page_number >= answer_list.number|add:-5 and page_number <= answer_list.number|add:5 %}
        {% if page_number == answer_list.number %}
        <li class="page-item active" aria-current="page">
            <a class="page-link" data-page="{{ page_number }}"
           href="javascript:void(0)">{{ page_number }}</a>
        </li>
        {% else %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
        </li>
        {% endif %}
        {% endif %}
        {% endfor %}
        <!-- 다음페이지 -->
        {% if question_list.has_next %}
        <li class="page-item">
            <a class="page-link" data-page="{{ question_list.next_page_number }}"
           href="javascript:void(0)">다음</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
        </li>
        {% endif %}
    </ul>
    <!-- 페이징처리 끝 -->
</div>
{% endblock %}
{% block script %}
<script type='text/javascript'>
    const delete_elements = document.getElementsByClassName("delete");
    Array.from(delete_elements).forEach(function(element) {
        element.addEventListener('click', function() {
            if(confirm("정말로 삭제하시겠습니까?")) {
                location.href = this.dataset.uri;
            };
        });
    });
    const recommend_elements = document.getElementsByClassName("recommend");
    Array.from(recommend_elements).forEach(function(element) {
    element.addEventListener('click', function() {
        if(confirm("정말로 추천하시겠습니까?")) {
            location.href = this.dataset.uri;
        };
    });
});
</script>
{% endblock %}

templates/pybo/question_list.html
{%extends 'base.html'%}
{% load pybo_filter %}
{% block content %}
<div class="container my-3">
    {% if category %}
    <h2 class="text-center">{{ category.name }}</h2>
    {% endif %}
    <div class="row my-3">
        <div class="col-6">
            <a href="{% url 'pybo:question_create' %}" class="btn btn-primary">질문 등록하기</a>
        </div>
        <div class="col-6">
            <div class="input-group">
                <input type="text" id="search_kw" class="form-control" value="{{ kw|default_if_none:'' }}">
                <div class="input-group-append">
                    <button class="btn btn-outline-secondary" type="button" id="btn_search">찾기</button>
                </div>
            </div>
        </div>
    </div>
    <table class="table">
        <thead>
            <tr class="text-center table-dark">
                <th>번호</th>
                <th style="width:50%">제목</th>
                <th>글쓴이</th>
                <th>작성일시</th>
            </tr>
        </thead>
        <tbody>
        {% if question_list %}
        {% for question in question_list %}
        <tr class="text-center">
            <td>
                {{ pagination.paginator.count |sub:pagination.start_index | sub:forloop.counter0|add:1 }}

            </td>
            <td class="text-start">
                <a href="{% url 'pybo:detail' question.id %}">{{ question.subject }}</a>
                {% if question.answer_set.count > 0 %}
                <span class="text-danger small mx-2">{{ question.answer_set.count }}</span>
                {% endif %}
            </td>
            <td><a href="{% url 'common:profile' question.author.id %}">{{ question.author.username }}</a> </td>  <!-- 글쓴이 추가 -->
            <td>{{ question.create_date }}</td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="4">질문이 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
    <!-- 페이징처리 시작 -->
    <ul class="pagination justify-content-center">
        <!-- 이전페이지 -->
        {% if pagination.has_previous %}
        <li class="page-item">
            <a class="page-link" data-page="{{ pagination.previous_page_number }}"
           href="javascript:void(0)">이전</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
        </li>
        {% endif %}
        <!-- 페이지리스트 -->
        {% for page_number in pagination.paginator.page_range %}
        {% if page_number >= pagination.number|add:-5 and page_number <= pagination.number|add:5 %}
        {% if page_number == pagination.number %}
        <li class="page-item active" aria-current="page">
            <a class="page-link" data-page="{{ page_number }}"
           href="javascript:void(0)">{{ page_number }}</a>
        </li>
        {% else %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
        </li>
        {% endif %}
        {% endif %}
        {% endfor %}
        <!-- 다음페이지 -->
        {% if pagination.has_next %}
        <li class="page-item">
            <a class="page-link" data-page="{{ pagination.next_page_number }}"
           href="javascript:void(0)">다음</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
        </li>
        {% endif %}
    </ul>
    <!-- 페이징처리 끝 -->
</div>
<form id="searchForm" method="get" action="{% url 'index' %}">
    <input type="hidden" id="kw" name="kw" value="{{ kw|default_if_none:'' }}">
    <input type="hidden" id="page" name="page" value="{{ page }}">
</form>
{% endblock %}
{% block script %}
<script type='text/javascript'>
const page_elements = document.getElementsByClassName("page-link");
Array.from(page_elements).forEach(function(element) {
    element.addEventListener('click', function() {
        document.getElementById('page').value = this.dataset.page;
        document.getElementById('searchForm').submit();
    });
});
const btn_search = document.getElementById("btn_search");
btn_search.addEventListener('click', function() {
    document.getElementById('kw').value = document.getElementById('search_kw').value;
    document.getElementById('page').value = 1;  // 검색버튼을 클릭할 경우 1페이지부터 조회한다.
    document.getElementById('searchForm').submit();
});
</script>
{% endblock %}