common/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views
from . import views
app_name = 'common'
urlpatterns = [
    # path('login/', auth_views.LoginView.as_view(template_name = 'common/login.html'), name='login'),
    path('login/', views.login_view, name='login'),

    path('logout/', views.logout_view, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('category/<int:category_id>', views.category, name='category'),
    # path('mypage/', views.profile, name='mypage'),
    path('profile_update/', views.profile_update, name='profile_update'),
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='registration/password_reset_form.html', success_url=reverse_lazy('common:password_reset_done')), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(success_url = reverse_lazy('common:password_reset_complete')), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('profile/<int:user_id>', views.profile, name='profile'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from pybo.views import base_views
from django.conf import settings # 추가

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')),
    path('common/', include('common.urls')), # 추가
    path('', base_views.index, name = 'index'),
    path('accounts/', include('allauth.urls')), # 추가
    # path('accounts/', include('accounts.urls')), # 추가
]
if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

pybo/urls.py
from django.urls import path
from .views import base_views, question_views, answer_views

app_name = 'pybo'

urlpatterns = [
    path('', base_views.index, name = 'index'),
    path('<int:question_id>/', base_views.detail, name = 'detail'),
    path('answer/create/<int:question_id>/', answer_views.answer_create, name = 'answer_create'),
    path('question/create/', question_views.question_create, name = 'question_create'),
    path('question/modify/<int:question_id>/', question_views.question_modify, name = 'question_modify'),
    path('question/delete/<int:question_id>/', question_views.question_delete, name = 'question_delete'),
    path('answer/modify/<int:answer_id>/', answer_views.answer_modify, name = 'answer_modify'),
    path('answer/delete/<int:answer_id>/', answer_views.answer_delete, name = 'answer_delete'),
    path('question/vote/<int:question_id>/', question_views.question_vote, name = 'question_vote'),
    path('answer/vote/<int:answer_id>/', answer_views.answer_vote, name = 'answer_vote'),
    path('comment/create/question/<int:question_id>/', question_views.comment_create_question, name = 'comment_create_question'),
    path('answer/comment/create/<int:answer_id>/', answer_views.comment_create_answer, name = 'comment_create_answer'),
]

common/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Profile (models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    nickname = models.CharField(max_length=20, blank=True)
    introduction = models.TextField(blank=True)
    image = models.ImageField(upload_to='profile/', blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    def __str__(self):
        return self.nickname

common/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, PasswordChangeForm
class UserForm(UserCreationForm):
    email = forms.EmailField(label="이메일")
    class Meta:
        model = User
        fields = ("username", "password1", "password2", "email")

class UserInfoForm(PasswordChangeForm):
    email = forms.EmailField(label="이메일")
    class Meta:
        model = User
        fields = ("username", "email")

common/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import redirect
from common.forms import UserForm, UserInfoForm
from pybo.models import Question, Category, Answer, Comment
from django.core.paginator import Paginator
from pybo.decorators import render_with_common
from django.contrib.auth.models import User

@render_with_common
def login_view(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('index')
    return {'context': {}, 'template': 'common/login.html'}
def logout_view(request):
    logout(request)
    return redirect('index')

# Create your views here.
@render_with_common
def signup(request):
    if request.method == "POST":
        form = UserForm(request.POST)
        print(form.is_valid())
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('index')
    else:
        form = UserForm()
    context = {'form': form}
    return {'context': context, 'template': 'common/signup.html'}
    # return render(request, 'common/signup.html', {'form': form})
@render_with_common
def category(request, category_id):
    posts = Question.objects.filter(category_id=category_id).order_by('-create_date')
    paginator = Paginator(posts, 10)
    page = paginator.get_page(1)
    category = Category.objects.get(pk=category_id)
    context = {'question_list':page, 'category':category, 'page':1}
    return {'context': context, 'template': 'pybo/question_list.html'}
    return render(request, 'pybo/question_list.html', context)

@render_with_common
def profile(request, user_id):
    if request.path == '/mypage/' and request.user.is_authenticated and request.user.id == user_id:
        user_id = request.user.id
    user = User.objects.get(pk=user_id)
    posts = Question.objects.filter(author=user).order_by('-create_date')
    paginator = Paginator(posts, 10)
    page = paginator.get_page(1)
    answers = Answer.objects.filter(author=user).order_by('-create_date')
    comments = Comment.objects.filter(author=user).order_by('-create_date')
    context = {'articles':page, 'page':1, 'user':user, 'answers':answers, 'comments':comments}
    return {'context': context, 'template': 'common/profile.html'}

@render_with_common
def profile_update(request):
    user = request.user
    if request.method == "POST":
        form = UserInfoForm(request.POST, instance=user)
        if form.is_valid():
            form.save()
            return redirect('common:mypage')
    else:
        form = UserInfoForm(instance=user)
    context = {'form': form}
    return {'context': context, 'template': 'common/user_info_change.html'}
    # return render(request, 'common/profile_update.html', context)

templates/common/login.html
{% extends "base.html" %}
{% block content %}
<div class="container my-3">
{% load socialaccount %}
{# <a href="{% provider_login_url 'kakao' method='oauth2' %}" class="social--login"></a>#}
{# <a href="{% provider_login_url 'google' method='oauth2' %}" class="social--login">#}
    <form method="post" action="{% url 'common:login' %}">
        {% csrf_token %}
        <input type="hidden" name="next" value="{{ next }}">  <!-- 로그인 성공후 이동되는 URL -->
        {% include "form_errors.html" %}
        <div class="mb-3">
            <label for="username">사용자ID</label>
            <input type="text" class="form-control" name="username" id="username"
                   value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="password">비밀번호</label>
            <input type="password" class="form-control" name="password" id="password"
                   value="{{ form.password.value|default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-primary">로그인</button>
    </form>
</div>
{% endblock %}

templates/common/mypage.html
{% extends "base.html" %}
{% block content %}
<!-- 내 정보를 표시하는 페이지 -->
    <h2 class="text-center">내 정보</h2>
    <div class="row my-3">
        <div class="col-6">
            <a href="{% url 'common:profile_update' %}" class="btn btn-primary">수정하기</a>
        </div>
        <div class="col-6">
            <a href="{% url 'common:password_change' %}" class="btn btn-primary">비밀번호 변경하기</a>
        </div>
    </div>
    <table class="table">
        <tbody>
            <tr>
                <th>사용자 이름</th>
                <td>{{ user.username }}</td>
            </tr>
            <tr>
                <th>이메일</th>
                <td>{{ user.email }}</td>
            </tr>
            <tr>
                <th>가입일시</th>
                <td>{{ user.date_joined }}</td>
            </tr>
        </tbody>
    </table>
    <!-- 내가 작성한 게시글 목록을 표시하는 페이지 -->
    <h2 class="text-center">내가 작성한 게시글</h2>
    <table class="table">
        <thead>
            <tr>
                <th>번호</th>
                <th>제목</th>
                <th>작성일시</th>
            </tr>
        </thead>
        <tbody>
            {% for article in articles %}
            <tr>
                <td>{{ article.pk }}</td>
                <td><a href="{% url 'pybo:detail' article.pk %}">{{ article.subject }}</a></td>
                <td>{{ article.create_date }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

{% endblock %}

templates/common/profile.html
{% extends "base.html" %}
{% block content %}
<!-- 내 정보를 표시하는 페이지 -->
    <!-- 만약 내 정보라면 -->
    {% if user == request.user %}
    <h2 class="text-center">내 정보</h2>
    {% else %}
    <h2 class="text-center">{{ user.username }}님의 정보</h2>
    {% endif %}
    {% if user == request.user %}
    <div class="row my-3">
        <div class="col-6">
            <a href="{% url 'common:profile_update' %}" class="btn btn-primary">수정하기</a>
        </div>
{#        <div class="col-6">#}
{#            <a href="{% url 'common:password_reset' %}" class="btn btn-primary">비밀번호 변경하기</a>#}
{#        </div>#}
    </div>
    {% endif %}
    <table class="table">
        <tbody>
            <tr>
                <th>사용자 이름</th>
                <td>{{ user.username }}</td>
            </tr>
            <tr>
                <th>이메일</th>
                <td>{{ user.email }}</td>
            </tr>
            <tr>
                <th>가입일시</th>
                <td>{{ user.date_joined }}</td>
            </tr>
        </tbody>
    </table>
    <!-- 내가 작성한 게시글 목록을 표시하는 페이지 -->
    <h2 class="text-center">내가 작성한 게시글</h2>
    <table class="table">
        <thead>
            <tr>
                <th>번호</th>
                <th>제목</th>
                <th>작성일시</th>
            </tr>
        </thead>
        <tbody>
        <div class = "container-md">
            {% for article in articles %}
            <tr>
                <td>{{ article.pk }}</td>
                <td><a href="{% url 'pybo:detail' article.pk %}">{{ article.subject }}</a></td>
                <td>{{ article.create_date }}</td>
            </tr>
            {% endfor %}
        </div>
        </tbody>
    </table>
    <!-- 내가 작성한 답변 목록을 표시하는 페이지 -->
    <h2 class="text-center">내가 작성한 답변</h2>
    <table class="table">
        <thead>
            <tr>
                <th>번호</th>
                <th>내용</th>
                <th>작성일시</th>
            </tr>
        </thead>
        <tbody>
        <div class = "container-md">
            {% for answer in answers %}
            <tr>
                <td>{{ answer.pk }}</td>
                <td><a href="{% url 'pybo:detail' answer.question.pk %}">{{ answer.content }}</a></td>
                <td>{{ answer.create_date }}</td>
            </tr>
            {% endfor %}
        </div>
        </tbody>
    </table>
    <!-- 내가 작성한 댓글 목록을 표시하는 페이지 -->
    <h2 class="text-center">내가 작성한 댓글</h2>
    <table class="table">
        <thead>
            <tr>
                <th>번호</th>
                <th>내용</th>
                <th>작성일시</th>
            </tr>
        </thead>
        <tbody>
        <div class = "container-md">
            {% for comment in comments %}
            <tr>
                <td>{{ comment.pk }}</td>
                {% if comment.question != null %}
                <td><a href="{% url 'pybo:detail' comment.question.pk %}">{{ comment.content }}</a></td>
                {% elif comment.answer != null %}
                <td><a href="{% url 'pybo:detail' comment.answer.question.pk %}">{{ comment.content }}</a></td>
                {% else %}
                <td>{{ comment.content }}</td>
                {% endif %}
                <td>{{ comment.create_date }}</td>
            </tr>
            {% endfor %}
        </div>
        </tbody>
    </table>
{% endblock %}

templates/common/signup.html
{% extends "base.html" %}
{% block content %}
<div class="container my-3">
    <form method="post">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="mb-3">
            <label for="username">사용자 이름</label>
            <input type="text" class="form-control" name="username" id="username"
                   value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="password1">비밀번호</label>
            <input type="password" class="form-control" name="password1" id="password1"
                   value="{{ form.password1.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="password2">비밀번호 확인</label>
            <input type="password" class="form-control" name="password2" id="password2"
                   value="{{ form.password2.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="email">이메일</label>
            <input type="text" class="form-control" name="email" id="email"
                   value="{{ form.email.value|default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-primary">생성하기</button>
    </form>
</div>
{% endblock %}

templates/common/user_info_change.html
{% extends "base.html" %}
{% block content %}
{% include "form_errors.html" %}
<div class="container my-3">
    <form method="post">
        {% csrf_token %}
        <div class="mb-3">
            <label for="username">사용자 이름</label>
            <input type="text" class="form-control" name="username" id="username"
                   value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="email">이메일</label>
            <input type="text" class="form-control" name="email" id="email"
                   value="{{ form.email.value|default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-primary">수정하기</button>
    </form>
{% endblock %}