common/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views
from . import views
app_name = 'common'
urlpatterns = [
    # path('login/', auth_views.LoginView.as_view(template_name = 'common/login.html'), name='login'),
    path('login/', views.login_view, name='login'),

    path('logout/', views.logout_view, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('category/<int:category_id>', views.category, name='category'),
    # path('mypage/', views.profile, name='mypage'),
    path('profile_update/', views.profile_update, name='profile_update'),
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='registration/password_reset_form.html', success_url=reverse_lazy('common:password_reset_done')), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(success_url = reverse_lazy('common:password_reset_complete')), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('profile/<int:user_id>', views.profile, name='profile'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from pybo.views import base_views
from django.conf import settings # 추가

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')),
    path('common/', include('common.urls')), # 추가
    path('', base_views.index, name = 'index'),
    path('accounts/', include('allauth.urls')), # 추가
    # path('accounts/', include('accounts.urls')), # 추가
]
if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

pybo/urls.py
from django.urls import path
from .views import base_views, question_views, answer_views

app_name = 'pybo'

urlpatterns = [
    path('', base_views.index, name = 'index'),
    path('<int:question_id>/', base_views.detail, name = 'detail'),
    path('answer/create/<int:question_id>/', answer_views.answer_create, name = 'answer_create'),
    path('question/create/', question_views.question_create, name = 'question_create'),
    path('question/modify/<int:question_id>/', question_views.question_modify, name = 'question_modify'),
    path('question/delete/<int:question_id>/', question_views.question_delete, name = 'question_delete'),
    path('answer/modify/<int:answer_id>/', answer_views.answer_modify, name = 'answer_modify'),
    path('answer/delete/<int:answer_id>/', answer_views.answer_delete, name = 'answer_delete'),
    path('question/vote/<int:question_id>/', question_views.question_vote, name = 'question_vote'),
    path('answer/vote/<int:answer_id>/', answer_views.answer_vote, name = 'answer_vote'),
    path('comment/create/question/<int:question_id>/', question_views.comment_create_question, name = 'comment_create_question'),
    path('answer/comment/create/<int:answer_id>/', answer_views.comment_create_answer, name = 'comment_create_answer'),
]

pybo/views/base_views.py
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from ..models import Question, Comment
from django.shortcuts import get_object_or_404
from django.db.models import Q, Count
from pybo.decorators import render_with_common, log_time
from django.core.cache import cache
from django.conf import settings
import redis
from ..cache_functions import save_dict_to_redis_as_string, get_dict_from_redis_string, get_element_from_redis_dict, add_to_redis_dict
import pickle

redis_client = redis.StrictRedis.from_url(settings.CACHES["default"]["LOCATION"])
# Create your views here.
def cache_page(page_obj, key):
    serialized_page = pickle.dumps(page_obj)
    redis_client.set(key, serialized_page)

def get_cached_page(key):
    serialized_page = redis_client.get(key)
    if serialized_page:
        return pickle.loads(serialized_page)
    return None

@log_time
@render_with_common
def index(request):
    page = request.GET.get('page', '1')
    kw = request.GET.get('kw', '')
    # redis_client.delete('index')
    # redis_client.delete('page_1')
    if not kw:
        cached_question_list = get_element_from_redis_dict("index", page)

        question_page_ids = cached_question_list
        page_object = get_cached_page(f"page_{page}")
    if kw or not cached_question_list:
        if kw:
            question_list = Question.objects.order_by('-create_date')
            question_list = question_list.filter(
                Q(subject__icontains=kw) |
                Q(content__icontains=kw) |
                Q(answer__content__icontains=kw) |
                Q(author__username__icontains=kw) |
                Q(answer__author__username__icontains=kw)
            ).distinct()
        else:
            question_list = Question.objects.only('id').order_by('-create_date')
        print(f">> 쿼리: {question_list.query}")

        paginator = Paginator(question_list, 10)

        try:
            page_object = paginator.page(page)
        except PageNotAnInteger:
            page_object = paginator.page(1)
        except EmptyPage:
            page_object = paginator.page(paginator.num_pages)
        print(f">> typeof page_object: {type(page_object)}")
        if not kw:
            question_page_ids = [q.id for q in page_object.object_list]
            add_to_redis_dict("index", page, question_page_ids)
            cache_page(page_object, f"page_{page}")
    else:
        print("using cache")

    questions = Question.objects.filter(id__in=question_page_ids).select_related('author').prefetch_related('answer_set').order_by('-create_date')
    print(f">> 쿼리: {questions.query}")
    context = {'pagination': page_object, 'question_list': questions, 'page': page, 'kw' : kw}

    return {'context': context, 'template': 'pybo/question_list.html'}

@log_time
@render_with_common
def detail(request, question_id):
    page = request.GET.get('page', '1')
    question = get_object_or_404(Question, pk=question_id)
    question.hits += 1
    question.save()
    answer_list = question.answer_set.all().order_by('-voter_count', '-create_date')
    print(f"query of answer_list: {answer_list.query}")
    paginator = Paginator(answer_list, 10)
    page_object = paginator.get_page(page)
    # print("page object %s" % page_object.count)

    context = {'question': question, 'answer_list': page_object}
    return {'context': context, 'template': 'pybo/question_detail.html'}

@log_time
@render_with_common
def recent_comment(request):
    comment_list = Comment.objects.order_by('-create_date')
    paginator = Paginator(comment_list, 10)
    page_object = paginator.get_page(1)
    context = {'comment_list': page_object}
    return {'context': context, 'template': 'pybo/recent_comment.html'}

templates/base.html
<!-- Required meta tags -->
{% load static %}
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

<!-- Bootstrap CSS -->
<link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
<!-- pybo CSS -->
<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
<title>Hello, pybo!</title>
</head>
<body>
<!-- 네비게이션바 -->
{% include "navbar.html" %}
<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->
<!-- 최근 등록된 답변 목록-->
<div class = "row d-flex justify-content-center">
{% include "recent_answer.html" %}
<!-- 최근 등록된 댓글 목록-->
{% include "recent_comment.html" %}
</div>
<!-- Bootstrap JS -->
<script src="{% static 'bootstrap.min.js' %}"></script>
<!-- 자바스크립트 Start -->
{% block script %}
{% endblock %}
<!-- 자바스크립트 End -->

</body>
<script>
$(document).ready(function(){
    $('.navbar-toggler').click(function(){
        $('#navbarSupportedContent').collapse('toggle');
    });
});
</script>

</html>

templates/form_errors.html
<!-- 필드 오류와 넌필드 오류를 출력한다. -->
{% if form.errors %}
<div class="alert alert-danger">
    {% for field in form %}
    <!-- 필드 오류 -->
    {% if field.errors %}
    <div>
        <strong>{{ field.label }}</strong>
        {{ field.errors }}
    </div>
    {% endif %}
    {% endfor %}
    <!-- 넌필드 오류 -->
    {% for error in form.non_field_errors %}
    <div>
        <strong>{{ error }}</strong>
    </div>
    {% endfor %}
</div>
{% endif %}

templates/navbar.html
<!-- 네비게이션바 -->
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'pybo:index' %}">Pybo</a>
        <button class="navbar-toggler" type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    {% if request.user.is_authenticated %}
                        <a class="nav-link" href="{% url 'common:logout' %}">{{ user.username }} (로그아웃)</a>
                        <a class="nav-link" href="{% url 'common:profile' request.user.id %}">내 정보</a>
                    {% else %}
                    <a class="nav-link" href="{% url 'common:login' %}">로그인</a>
                    {% endif %}
                </li>
                <li>
                    {% if not user.is_authenticated %}
                    <a class="nav-link" href="{% url 'common:signup' %}">회원가입</a>
                    {% endif %}
                </li>
            <li class="nav-item">
            <a class = "nav-link" href="{% url 'common:password_reset' %}">비밀번호 재설정</a>
                {% for category in category_list %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'common:category' category.id %}">{{ category.name }}</a>
                </li>
                {% endfor %}
            </ul>
        </div>
    </div>
</nav>

templates/recent_answer.html
<!-- 최근 등록된 답변 목록 -->
<div class="col-sm-5">
    <h3 class="border-bottom py-2">최근 등록된 답변</h3>
    <ul>
        {% for answer in recent_answers %}
        <li>
            <a href="{% url 'pybo:detail' answer.question.pk %}">{{ answer.content }}</a>
            <span>{{ answer.created_at }}</span>
        </li>
        {% endfor %}
    </ul>
</div>

templates/recent_comment.html
<!-- 최근 등록된 댓글 모음 -->
<div class="col-sm-5">
    <h3 class="border-bottom py-2">최근 댓글</h3>
    <ul>
        {% for comment in recent_comments %}
        <li>
            {% if comment.question != null %}
                <a href="{% url 'pybo:detail' comment.question.id %}">
            {% elif comment.answer.question != null %}
                <a href="{% url 'pybo:detail' comment.answer.question.id %}">
            {% endif %}
                {{ comment.content }}
            </a>
            <span>by {{ comment.author.username }} at {{ comment.create_date }}</span>
        </li>
        {% endfor %}
    </ul>
</div>